import { Toaster } from 'react-hot-toast';
import './globals.css';
import Providers from '@/components/Providers';
import { CartProvider } from '@/components/CartContext';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <CartProvider>
                        <Toaster />
                        {children}
                    </CartProvider>
                </Providers>
            </body>
        </html>
    );
}
