import { Text } from '@/components';
import { DashboardNav, Navbar, MiniNavbar } from '@/components';
import { Button } from '@/components/ui';
import { Rocket } from '@/components/ui/Icon';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="min-h-screen min-w-screen bg-cardPrimary">
            <MiniNavbar />
            <Navbar />
            <div className="container mx-auto flex flex-col gap-5">
                <DashboardNav />
                {children}
            </div>
        </div>
    );
}
