import MiniNavbar from '@/components/MiniNavbar';
import Navbar from '@/components/Navbar';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <MiniNavbar />
            <Navbar />
            <div className="container mx-auto">{children}</div>
        </>
    );
}
