import MiniNavbar from '@/components/MiniNavbar';
import Navbar from '@/components/Navbar';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="container mx-auto">
            <MiniNavbar />
            <Navbar />
            {children}
        </div>
    );
}
