import { Text } from '@/components';
import AuthNav from '@/components/AuthNav';
import { Button } from '@/components/ui';
import { LeftArrow } from '@/components/ui/Icon';
import Link from 'next/link';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface ILayout {
    path: string;
    children: React.ReactNode;
}

export default function RootLayout({ path, children }: ILayout) {
    console.log(children);

    return (
        <div className="flex flex-col items-center justify-between bg-primary w-screen h-screen p-10">
            <div className="flex justify-between container">
                <AuthNav />
            </div>

            {children}

            <Text variant="titleSm" className="flex">
                Forgot your Password?
            </Text>
        </div>
    );
}
